[PERF-227] Statistics Logging
Ed-Fi-Exchange-OSS/Suite-3-Performance-Testing pull request #17
Opened 2022-03-15 18:04 UTC by stephenfuqua

2022-03-15 18:06 UTC, stephenfuqua commented on src/edfi-paging-test/tests/helpers/test_request_logger.py
> +                "edfi_paging_test.helpers.request_logger._request_log", request_log
@vimayya if you ever need to mock a module-level variable or function (outside of a class/object), then this `mocker` object is very useful, from the library `pytest-mock`. You can create a `patch` without it, but you'll also need to restore the original. With the `mocker` object, the original version of the variable or function is automatically restored.

2022-03-18 00:15 UTC, stephenfuqua commented on .github/workflows/edfi_paging_test.yml
> +            reporter: java-junit
These two new actions will capture the unit test and static type test output directly in GitHub Actions.

2022-03-18 00:15 UTC, stephenfuqua commented on eng/build.py
> +            "--junitxml=pytest-junit.xml"
Unit test output to XML for the reporting mentioned above.

2022-03-18 00:15 UTC, stephenfuqua commented on src/edfi-paging-test/edfi_paging_test/api/paginated_result.py
> -        return self._current_page_items
Properties like this are actually not common in Python, since all of the variables are public anyway.

2022-03-18 00:15 UTC, stephenfuqua commented on src/edfi-paging-test/edfi_paging_test/api/request_client.py
> -                f"{response.reason} ({response.status_code}): {response.text}"
I removed the retry process. Thus no need to raise an error.

2022-03-18 00:15 UTC, stephenfuqua commented on src/edfi-paging-test/edfi_paging_test/performance_tester.py
> +    total_count = request_client.get_total()
this is the original content from `__main__`.

2022-03-18 00:15 UTC, stephenfuqua commented on src/edfi-paging-test/edfi_paging_test/api/request_client.py
> +            items.extend(pagination_result.current_page_items)
I didn't notice before that we had `items + list()` - that's actually a dangerous pattern in Python. Better to use `extend()`.

2022-03-21 19:48 UTC, vimayya requested changes

2022-03-21 19:48 UTC, vimayya commented on src/edfi-paging-test/.gitignore
> +*.xml
Should the detail and summary reports be ignored as well? If full path is not given for output directory, reports get created at the repo root.

2022-03-21 19:48 UTC, vimayya commented on src/edfi-paging-test/edfi_paging_test/reporter/measurement.py
> +    def timeit(callback: Callable[[], T]) -> Tuple[float, T]:
timeit static method feels a bit misplaced inside Measurement class. Consider moving it to out to keep Measurement a simple data class.

2022-03-22 14:05 UTC, stephenfuqua commented on src/edfi-paging-test/tests/reporter/test_measurement.py
> +    def describe_given_asdfasdf():
Ah yes, that was supposed to be a placeholder for myself as I was trying to figure out what I even wanted to do ....

2022-03-22 16:54 UTC, stephenfuqua commented on src/edfi-paging-test/edfi_paging_test/helpers/output_format.py
> +    JSON = "json"
You're right. I had the `__missing__` method backwards: thought it was referring to the Enum, e.g. `JSON`, or `CSV`. Obviously did not test it appropriately. Just tested and confirmed that it is the value, not the name, and thus changed to `.lower()` in `__missing__`.

2022-03-22 19:21 UTC, vimayya approved these changes

2022-03-22 19:21 UTC, merged