[PERF-277] Update extension lab testing documentation
Ed-Fi-Exchange-OSS/Suite-3-Performance-Testing pull request #58
Opened 2022-09-18 20:33 UTC by vimayya

2022-09-21 13:33 UTC, stephenfuqua commented on docs/lab-extension-testing.md
> +| Type     | Name                                                                       | # reqs |    # fails  |    Avg |     Min |    Max  | Med  |   req/s | failures/s|
This `Name` column seems far wider than needed - can it be reformatted?

You might already know this tip: I find that the VS Code extension "Markdown All in One" does a great job of this when you use the VS Code "format document" command.

2022-09-21 13:33 UTC, stephenfuqua commented on src/edfi-performance-test/README.md
Should the images above be in the `docs/images` directory instead of `docs/old/images`?

2022-09-26 17:50 UTC, andonyns commented on docs/how-to-create-tests.md
> +  from edfi_performance_test.api.client.ed_fi_api_client import EdFiAPIClient
The preview for this section is not loading correctly. See it here: https://github.com/Ed-Fi-Exchange-OSS/Suite-3-Performance-Testing/blob/PERF-277/docs/how-to-create-tests.md#2-client

After testing locally it seems related to the tabs in the area. This loads on the VS Code Preview
![image](https://user-images.githubusercontent.com/5459528/192345828-87dd30d1-e0c5-40ea-add4-1726f2b8dde1.png)

2022-09-26 20:52 UTC, andonyns requested changes
The only change needed is the code snippet that is not being rendered correctly

2022-09-27 16:34 UTC, andonyns approved these changes

2022-09-27 16:34 UTC, merged