[PERF-317] Run Paging Test on github Action
Ed-Fi-Exchange-OSS/Suite-3-Performance-Testing pull request #95
Opened 2023-10-25 20:13 UTC by JBrenesSimpat

2023-10-31 19:55 UTC, semalaiappan commented on .github/workflows/Package_pre_release.yml
> +name: Package Pre-Release
Avoid Underscore in file name for any file under workflows

2023-10-31 19:57 UTC, semalaiappan commented on .github/workflows/Paging_test.yml
> +    AzureTestVmUsername: ${{ secrets.AZURE_TEST_VM_USER_NAME }}
Use underscore here . example AZURE_TEST_VM_USERNAME: ${{ secrets.AZURE_TEST_VM_USER_NAME }}

2023-10-31 19:58 UTC, semalaiappan commented on .github/workflows/Paging_test.yml
> +
Remove whitespaces lines here

2023-10-31 19:59 UTC, semalaiappan requested changes
Added my review comments

2024-06-12 22:52 UTC, vimayya approved these changes

2024-06-13 14:20 UTC, semalaiappan requested changes

2024-06-13 14:20 UTC, semalaiappan commented on .github/workflows/run_paging_test.yml
> +        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
Can you update to actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0 this one also ?

2024-06-13 16:48 UTC, semalaiappan approved these changes

2024-06-13 16:48 UTC, merged