[PERF-319] Run Volume Test on github Action
Ed-Fi-Exchange-OSS/Suite-3-Performance-Testing pull request #97
Opened 2023-10-30 15:23 UTC by JBrenesSimpat

2023-10-31 20:06 UTC, semalaiappan commented on .github/workflows/Volume_test.yml
> +name: Run Volome Test
Remove Underscore in filename

2023-10-31 20:07 UTC, semalaiappan commented on .github/workflows/Volume_test.yml
> +name: Run Volome Test
Spelling mistake in Volome .  Volume

2023-10-31 20:25 UTC, semalaiappan commented on .github/workflows/Volume_test.yml
> +
Remove Whitespace lines here

2023-10-31 20:25 UTC, semalaiappan commented on .github/workflows/Volume_test.yml
> +
Remove whitespace lines here

2023-10-31 20:26 UTC, semalaiappan requested changes
Review comments updated

2024-06-12 22:20 UTC, vimayya approved these changes

2024-06-13 14:18 UTC, semalaiappan approved these changes

2024-06-13 14:18 UTC, merged